# Generated by Django 4.1.3 on 2022-11-29 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comps', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product_status',
            new_name='ProductStatus',
        ),
    ]
