# Generated by Django 4.1.3 on 2022-11-30 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0001_initial'),
        ('comps', '0003_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='oauth.authuser'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
